# Generated by Django 4.2.3 on 2023-08-03 07:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_cuentas', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteprofile',
            name='catalogo_cuentas',
            field=models.ManyToManyField(blank=True, to='catalogo_cuentas.catalogocuentas'),
        ),
        migrations.AddField(
            model_name='clienteprofile',
            name='country',
            field=models.ForeignKey(blank=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='catalogo_cuentas.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contadorprofile',
            name='catalogo_cuentas',
            field=models.ManyToManyField(blank=True, to='catalogo_cuentas.catalogocuentas'),
        ),
        migrations.AddField(
            model_name='contadorprofile',
            name='country',
            field=models.ForeignKey(blank=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='catalogo_cuentas.country'),
            preserve_default=False,
        ),
    ]
