# Generated by Django 4.2.3 on 2023-08-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_clienteprofile_catalogo_cuentas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteprofile',
            name='name',
            field=models.CharField(default='contador', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contadorprofile',
            name='name',
            field=models.CharField(default='cliente', max_length=100),
            preserve_default=False,
        ),
    ]
