# Generated by Django 4.2.3 on 2023-08-04 00:54

import apps.user.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogo_cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorProfile',
            fields=[
                ('name', models.CharField(blank=True, max_length=100)),
                ('contador_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.IntegerField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=100)),
                ('icono_perfil', models.ImageField(blank=True, upload_to=apps.user.models.user_directory_path)),
                ('catalogo_cuentas', models.ManyToManyField(blank=True, to='catalogo_cuentas.catalogocuentas')),
                ('country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo_cuentas.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteProfile',
            fields=[
                ('name', models.CharField(blank=True, max_length=100)),
                ('cliente_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.IntegerField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=100)),
                ('icono_perfil', models.ImageField(blank=True, upload_to=apps.user.models.user_directory_path)),
                ('catalogo_cuentas', models.ManyToManyField(blank=True, to='catalogo_cuentas.catalogocuentas')),
                ('country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo_cuentas.country')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
