# Generated by Django 4.2.3 on 2023-08-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_contadorprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contadorprofile',
            name='especialidad',
            field=models.CharField(default='contabilidad', max_length=100),
            preserve_default=False,
        ),
    ]
