# Generated by Django 4.2.3 on 2023-08-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_contadorprofile_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='contadorprofile',
            name='cliente',
            field=models.ManyToManyField(blank=True, to='user.clienteprofile'),
        ),
    ]
