# Generated by Django 4.2.3 on 2023-08-04 11:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_cuentas', '0002_remove_catalogocuentas_id_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogocuentas',
            name='cliente',
            field=models.UUIDField(blank=True, default=uuid.UUID('6bbb7ee6-270c-4dbe-92a7-b1780f3f6fee')),
        ),
        migrations.AddField(
            model_name='catalogocuentas',
            name='contador',
            field=models.UUIDField(blank=True, default=uuid.UUID('492f5fe5-ccb3-4649-b371-79b310022424')),
        ),
    ]
