# Generated by Django 4.2.3 on 2023-08-04 12:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_cuentas', '0003_catalogocuentas_cliente_catalogocuentas_contador'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogocuentas',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalogocuentas',
            name='cliente',
            field=models.UUIDField(blank=True, default=uuid.UUID('20e0a5a4-3745-4ae9-9d6c-38eb2e28e966')),
        ),
        migrations.AlterField(
            model_name='catalogocuentas',
            name='contador',
            field=models.UUIDField(blank=True, default=uuid.UUID('588d5f0c-2e60-45b1-97fe-91c8b959b34c')),
        ),
    ]
