# Generated by Django 4.2.3 on 2023-07-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type_bank', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_account', models.CharField(max_length=100)),
                ('activos', models.IntegerField()),
                ('pasivos', models.IntegerField()),
                ('id_cuenta', models.IntegerField()),
                ('mov_deudor', models.IntegerField()),
                ('mov_acreedor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoCuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_created', models.CharField(max_length=100)),
                ('type_catalog', models.CharField(max_length=100)),
                ('accounts', models.ManyToManyField(to='catalogo_cuentas.cuenta')),
                ('bancos', models.ManyToManyField(to='catalogo_cuentas.banco')),
            ],
        ),
    ]
