# Generated by Django 4.2.3 on 2023-07-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pasivo', models.IntegerField(blank=True)),
                ('date', models.DateField(auto_now=True)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('subtype', models.CharField(blank=True, max_length=100)),
                ('subsubtype', models.CharField(blank=True, max_length=100)),
                ('name_activo', models.CharField(blank=True, max_length=100)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bank', models.CharField(blank=True, max_length=100)),
                ('name_bank', models.CharField(blank=True, max_length=100)),
                ('type_bank', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_caja', models.CharField(blank=True, max_length=100)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_account', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('activos', models.IntegerField(blank=True)),
                ('pasivos', models.IntegerField(blank=True)),
                ('id_cuenta', models.IntegerField(blank=True)),
                ('mov_deudor', models.IntegerField(blank=True)),
                ('mov_acreedor', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pasivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pasivo', models.IntegerField(blank=True)),
                ('date', models.DateField(auto_now=True)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('subtype', models.CharField(blank=True, max_length=100)),
                ('subsubtype', models.CharField(blank=True, max_length=100)),
                ('name_pasivo', models.CharField(blank=True, max_length=100)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoCuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_catalogo', models.CharField(blank=True, max_length=100)),
                ('id_created', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('type_catalog', models.CharField(blank=True, max_length=100)),
                ('patrimonio_neto', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('gastos', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('ingresos', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('saldo_intermediario', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('cuentas_de_orden', models.ManyToManyField(blank=True, to='catalogo_cuentas.cuenta')),
            ],
        ),
    ]
