# Generated by Django 4.2.3 on 2023-07-28 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogocuentas',
            name='activos',
            field=models.ManyToManyField(blank=True, to='catalogo_cuentas.activos'),
        ),
        migrations.AddField(
            model_name='catalogocuentas',
            name='pasivos',
            field=models.ManyToManyField(blank=True, to='catalogo_cuentas.pasivos'),
        ),
    ]
