# Generated by Django 4.2.3 on 2023-08-04 14:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_cuentas', '0002_alter_catalogocuentas_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogocuentas',
            name='cliente',
            field=models.UUIDField(blank=True, default=uuid.UUID('c8ca1a5b-f70e-4ac1-af09-6c7c959c0807')),
        ),
        migrations.AlterField(
            model_name='catalogocuentas',
            name='contador',
            field=models.UUIDField(blank=True, default=uuid.UUID('0db5475e-0fa4-46f9-8e8e-3d8c0ab27aef')),
        ),
    ]
