# Generated by Django 4.2.3 on 2023-08-04 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_cuentas', '0003_alter_catalogocuentas_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogocuentas',
            name='cliente',
            field=models.UUIDField(blank=True, default=uuid.UUID('ae564b9e-d114-40d0-b014-5c25b199c111')),
        ),
        migrations.AlterField(
            model_name='catalogocuentas',
            name='contador',
            field=models.UUIDField(blank=True, default=uuid.UUID('ac6b94b0-0f55-4185-af6a-761b6a5d626e')),
        ),
    ]
