# Generated by Django 4.2.3 on 2023-07-28 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_cuentas', '0004_alter_catalogocuentas_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activos',
            old_name='id_pasivo',
            new_name='id_activo',
        ),
    ]
