# Generated by Django 4.2.3 on 2023-08-04 15:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_cuentas', '0005_alter_catalogocuentas_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogocuentas',
            name='cliente',
            field=models.UUIDField(blank=True, default=uuid.UUID('95748381-7444-448f-bb84-e2922c95d3dc')),
        ),
        migrations.AlterField(
            model_name='catalogocuentas',
            name='contador',
            field=models.UUIDField(blank=True, default=uuid.UUID('eda4676f-caba-47ee-9615-f80f966c6532')),
        ),
    ]
