# Generated by Django 4.2.3 on 2023-07-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_cuentas', '0005_rename_id_pasivo_activos_id_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
    ]
