# Generated by Django 4.2.3 on 2023-07-29 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_cuentas', '0007_delete_caja_catalogocuentas_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogocuentas',
            name='banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo_cuentas.banco'),
        ),
    ]
