# Generated by Django 4.2.3 on 2023-08-02 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_cuentas', '0008_alter_catalogocuentas_banco'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pasivos',
            new_name='Activo',
        ),
        migrations.RenameModel(
            old_name='Activos',
            new_name='Pasivo',
        ),
        migrations.RenameField(
            model_name='activo',
            old_name='id_pasivo',
            new_name='id_activo',
        ),
        migrations.RenameField(
            model_name='activo',
            old_name='name_pasivo',
            new_name='name_activo',
        ),
        migrations.RenameField(
            model_name='pasivo',
            old_name='id_activo',
            new_name='id_pasivo',
        ),
        migrations.RenameField(
            model_name='pasivo',
            old_name='name_activo',
            new_name='name_pasivo',
        ),
    ]
